bind                = "0.0.0.0:10000"
workers             = 1          # MUST be 1 — each worker loads ~400MB model
threads             = 1
timeout             = 300        # 5 min — covers cold model load + predict()
preload_app         = False      # let lazy-load in get_model() work
worker_class        = "sync"
max_requests        = 50
max_requests_jitter = 5
loglevel            = "info"
accesslog           = "-"
errorlog            = "-"
