bind              = "0.0.0.0:10000"
workers           = 1        # 1 worker only — each loads ~300MB model
threads           = 1
timeout           = 120      # model.predict() can take 40s on cold CPU
preload_app       = False    # let lazy-load in get_model() work correctly
worker_class      = "sync"
max_requests      = 100      # recycle worker to prevent slow memory creep
max_requests_jitter = 10
loglevel          = "info"
accesslog         = "-"
errorlog          = "-"
